### ISSUE TITLE
Seeing this very often in the log 5.32

### ISSUE THREAD

**Issue by tapashdatta** [twomice/com.joineryhq.hideactivitytypes#6]
CRM_Hideactivitytypes_DAO_ActivityMask needs to be regenerated. Missing getEntityTitle method. Array ( [civi.tag] => deprecated )

**Comment by twomice** [comment]
Note. Investigating. Thanks @tapashdatta

**Comment by twomice** [comment]
Fixed in #7 / e6cc20f8ccc168bcd2566953e2c98696cc53cf81.
No new release scheduled yet, but this will be in it when it happens.
Thanks for the report @tapashdatta .
